<a href="https://colab.research.google.com/github/sbbwoy/ESAA/blob/main/100_Numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print(np.__version__)
print(np.show_config())

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
a = np.zeros(10)

#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
a.size*a.itemsize

80

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
np.info(np.add)

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
a[4] = 1
a

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
b = np.arange(10, 50)

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
np.sort(b) [::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
np.arange(0, 9).reshape(3,-1)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
x = [1,2,0,0,4,0]
np.nonzero(x)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
Z = np.eye(3,3)
Z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
Z = np.random.random((3,3,3))
Z

array([[[0.13526111, 0.34921145, 0.371492  ],
        [0.49700114, 0.66886399, 0.56051687],
        [0.77097522, 0.60997499, 0.92851016]],

       [[0.2008551 , 0.79370931, 0.99067067],
        [0.88833991, 0.38479159, 0.37775423],
        [0.55008145, 0.40195799, 0.14059957]],

       [[0.49611396, 0.22090564, 0.03056501],
        [0.9540898 , 0.43880495, 0.65426168],
        [0.84842464, 0.98106237, 0.40942799]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
Z = np.random.random((10, 10))
print(Z.min(), Z.max())

0.00333738636699088 0.9926300935844842


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
Z = np.random.random((30))
Z.mean()

0.598987434046495

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
Z = np.zeros((3,3))
Z[[0,-1]] = 1
Z[:,[0,-1]] = 1
Z

array([[1., 1., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
Z = np.ones((5, 5))
Z[1:-1, 1:-1] = 0
Z

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
print(0 * np.nan) # NaN 사칙연산 --> NaN
print(np.nan == np.nan) # NaN 대소비교 불가
print(np.inf > np.nan) #무한>Not a Number X
print(np.nan - np.nan) 
print(np.nan in set([np.nan])) #NaN 하나쯤 있겠지...
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
Z = np.diag(1+np.arange(4),k=-1) #k로 조절 가능...!!!
Z

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
Z = np.zeros((8,8))
Z[::2,1::2] = 1
Z[1::2,::2] = 1
Z

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [19]:
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [23]:
np.tile(np.array([[0,1],[1,0]]),(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [24]:
z = np.random.random((5, 5))
z = (z -np.mean(z)/np.std(z))
z

array([[-2.16434876, -1.77992875, -1.70421622, -1.86149534, -1.37894918],
       [-1.43145511, -1.55571986, -1.61602872, -1.75592773, -1.79961032],
       [-1.86123832, -1.5871626 , -1.76699585, -2.03955857, -1.33743102],
       [-1.47480664, -1.38791556, -1.85942408, -1.283505  , -1.24597333],
       [-1.75851903, -1.37873667, -1.52290382, -2.08509011, -1.74031417]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [27]:
col = np.dtype([('r',np.ubyte, 1), ('g',np.ubyte, 1), ('b',np.ubyte, 1), ('a',np.ubyte, 1)])
col

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """Entry point for launching an IPython kernel.


dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [28]:
A = np.random.random((5, 3))
B = np.random.random((3, 2))
A@B

array([[0.40358393, 0.89853705],
       [0.37107975, 1.24852812],
       [0.39154847, 1.26812694],
       [0.48841364, 1.28746221],
       [0.25694393, 0.97994416]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [30]:
Z = np.arange(11)
Z[(3<Z)&(Z<8)] *= -1
Z

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [31]:
np.sum(range(5),-1)

10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [32]:
Z<Z>Z

ValueError: ignored

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [33]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (★☆☆)

In [34]:
Z = np.random.uniform(-10, 10, 10)
np.copysign(np.ceil(np.abs(Z)), Z)      #copysign: 해당 값을 기존 Z의 부호대로 바꿔줌

array([ 7., -8.,  2., -7., -3., -6.,  6., -1.,  4., 10.])

#### 30. How to find common values between two arrays? (★☆☆)

In [35]:
A = np.random.randint(0, 10, 10)
B = np.random.randint(0, 10, 10)
print(A, B)
np.intersect1d(A, B)        #공통 인자 찾아냄

[5 9 8 7 7 0 2 0 1 9] [9 9 8 3 4 8 0 2 8 4]


array([0, 2, 8, 9])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [43]:
defaults = np.seterr(all = "ignore")
Z = np.ones(1) / 0 
np.seterr(**defaults)       #돌려놓기
with np.errstate(divide='ignore'):
    Z = np.ones(1)/0

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [44]:
False

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [46]:
yesterday = np.datetime64('today','D') - np.timedelta64(1,'D')
today = np.datetime64('today','D')
tomorrow = np.datetime64('today','D') + np.timedelta64(1,'D')
print(yesterday, today, tomorrow)

2021-09-16 2021-09-17 2021-09-18


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [48]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [49]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3

np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [50]:
Z = np.random.uniform(0, 10, 10)

print(Z - Z%1)
print(np.floor(Z))
print(np.ceil(Z))
print(Z.astype(int))
print(np.trunc(Z))      #소수 절사

[4. 0. 8. 3. 4. 4. 9. 5. 8. 7.]
[4. 0. 8. 3. 4. 4. 9. 5. 8. 7.]
[ 5.  1.  9.  4.  5.  5. 10.  6.  9.  8.]
[4 0 8 3 4 4 9 5 8 7]
[4. 0. 8. 3. 4. 4. 9. 5. 8. 7.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [51]:
Z = np.zeros((5, 5))
Z += np.arange(5)
Z

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [52]:
def generator():
    for i in range(10):
        yield i
Z = np.fromiter(generator(), dtype = "float", count= -1)    #표현 가능한 객체로부터 새로운 1차원 배열 생성
Z

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [53]:
Z = np.linspace(0, 1, 11, endpoint = False)[1:]
Z

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [54]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.14339934 0.18976966 0.33272283 0.45847639 0.55961549 0.61497709
 0.66527126 0.69262444 0.92990416 0.93914417]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [55]:
A  = np.arange(10)
np.add.reduce(A)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [56]:
A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 2, 5)
print(np.allclose(A, B))
print(np.array_equal(A, B))

False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [57]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1    # error

ValueError: ignored

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [59]:
Z = np.random.random((10, 2))
X, Y = Z[:, 0], Z[:, 1]
R = np.sqrt(X**2+Y**2)
P = np.arctan2(Y, X)
print(R)
print(P)

[0.72747842 0.5643711  0.99582705 0.88253649 0.87101037 1.04942228
 0.5204565  0.54719809 0.63476772 0.96600016]
[0.24890941 0.93802734 0.46447424 1.39311626 0.52091584 1.08400127
 1.09267607 0.82302735 1.17131542 1.19326562]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [60]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)


[0.42620984 0.51500079 0.25472979 0.63718942 0.69336071 0.46198834
 0.11305901 0.         0.20698299 0.02563386]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [63]:
Z = np.zeros((5,5),[('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0, 1, 5), np.linspace(0, 1, 5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [65]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [66]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)      #표현 가능한 가장 작은 값

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [69]:
np.set_printoptions(threshold=0)        #threshold는 요약을 하는 배열 요소의 총 개수
Z = np.zeros((16, 16))
Z

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [70]:
Z = np.random.randint(0, 10, 10)
print(Z)
Z[Z.argmin()]

[7 9 9 ... 3 6 5]


2

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [72]:
Z = np.zeros(10,[('position',[('x',float,1),
                             ('y',float,1)]),
                ('color', [('r',float,1),
                          ('g',float,1),
                          ('b',float,1)])])
Z

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


array([((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ..., ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.))],
      dtype=[('position', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', '<f8'), ('g', '<f8'), ('b', '<f8')])])

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [74]:
Z = np.random.random((10, 2))
X,Y = np.atleast_2d(Z[:,0],Z[:,1])
D = np.sqrt( (X - X.T)**2 + (Y - Y.T)**2)
print(D)

[[0.         0.53016375 0.97400437 ... 0.78258133 0.75105895 0.10364479]
 [0.53016375 0.         0.64320669 ... 0.25520716 0.42413373 0.46155976]
 [0.97400437 0.64320669 0.         ... 0.55139708 0.23265181 0.96506423]
 ...
 [0.78258133 0.25520716 0.55139708 ... 0.         0.39805446 0.71672411]
 [0.75105895 0.42413373 0.23265181 ... 0.39805446 0.         0.73570941]
 [0.10364479 0.46155976 0.96506423 ... 0.71672411 0.73570941 0.        ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [75]:
Z = np.arange(10, dtype=np.float32)
Z = Z.astype(np.int32, copy=False)
Z

array([0, 1, 2, ..., 7, 8, 9], dtype=int32)

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [80]:
from io import StringIO
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")

Z = np.genfromtxt(s,delimiter=",",dtype=np.int)
print(Z)


[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [82]:
Z = np.arange(9).reshape(3, 3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [83]:
X,Y = np.meshgrid(np.linspace(-1,1,10),np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma,mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 ... 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 ... 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 ... 0.73444367 0.63331324 0.51979489]
 ...
 [0.51979489 0.63331324 0.73444367 ... 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 ... 0.63331324 0.54610814 0.44822088]
 [0.36787944 0.44822088 0.51979489 ... 0.51979489 0.44822088 0.36787944]]


#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [84]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [87]:
X = np.random.rand(5, 10)

Y = X - X.mean(axis = 1, keepdims=True)
print(Y)

[[-0.4472525  -0.50395492  0.2788489  ... -0.21558981 -0.41329298
  -0.18941579]
 [ 0.0630628   0.18000892 -0.25406048 ...  0.06351236 -0.40203485
  -0.23360212]
 [ 0.33749884 -0.24723307  0.17982925 ... -0.36086911 -0.47950817
   0.06701291]
 [-0.4654832   0.14726533 -0.31872542 ... -0.34656026  0.12515742
  -0.01910202]
 [ 0.4690951  -0.43460979 -0.04889288 ... -0.097439    0.1022125
   0.44701828]]


#### 59. How to sort an array by the nth column? (★★☆)

In [90]:
Z = np.random.randint(0, 10, (3, 3))
print(Z)
print(Z[Z[:,1].argsort()])

[[3 5 2]
 [9 4 2]
 [3 3 8]]
[[3 3 8]
 [9 4 2]
 [3 5 2]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [94]:
Z = np.random.randint(0,3,(3,10))
print(Z)
print((~Z.any(axis=0)).any())       

[[0 0 2 ... 0 0 0]
 [1 2 2 ... 1 2 0]
 [1 1 0 ... 2 0 0]]
True


#### 61. Find the nearest value from a given value in an array (★★☆)

In [95]:
Z = np.random.uniform(0,1,10)
z = 0.5 
m = Z.flat[np.abs(Z-z).argmin()]
print(m)

0.5696204867282206


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [96]:
A = np.arange(3).reshape(1,3)
B = np.arange(3).reshape(3,1)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x+y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [97]:
Z = np.ones(10)
a = np.random.randint(0,len(Z),20)
np.add.at(Z,a,1)
print(a)
print(Z)

[0 3 7 ... 4 6 1]
[2. 4. 2. ... 4. 1. 2.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [98]:
X = [1,2,3,4,5,6]
I = [3,4,5,6,7,8]
F = np.bincount(I,X)
print(F)

[0. 0. 0. ... 4. 5. 6.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [99]:
img = np.random.randint(0,2,(16,16,3)).astype(np.ubyte)
F = img[...,0]*(256*256) + img[...,1]*256 + img[...,2]
print(len(np.unique(F)))

8


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [100]:
A = np.random.randint(0, 10, (3, 4, 3, 4))
A.sum(axis = (-2, -1))

array([[47, 83, 42, 48],
       [59, 53, 42, 46],
       [57, 62, 63, 66]])

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [102]:
import pandas as pd
D = np.random.uniform(0, 1, 100)
S = np.random.randint(0, 10, 100)
pd.Series(D).groupby(S).mean()

0    0.378982
1    0.495013
2    0.284771
3    0.402897
4    0.393107
5    0.581908
6    0.331192
7    0.590848
8    0.585981
9    0.529519
dtype: float64

#### 69. How to get the diagonal of a dot product? (★★★)

In [103]:
A = np.random.uniform(0, 1, (5, 5))
B = np.random.uniform(0, 1, (5, 5))
np.diag(np.dot(A, B))

array([0.71039409, 1.76343156, 1.75599761, 1.32837565, 2.2823782 ])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [106]:
Z = np.arange(1, 6)
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1) *(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. ... 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [107]:
A = np.ones((5, 5, 3))
B = 2*np.ones((5, 5))
print(A* B[:, :, None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [108]:
A = np.arange(25).reshape(5, 5)
A[[0, 1]] = A[[1, 0]]
A

array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [109]:
faces = np.random.randint(0, 100, (10, 3))
F = np.roll(faces.repeat(2, axis = 1), -1, axis = 1)
F = F.reshape(len(F)*3, 2)
F = np.sort(F, axis = 1)
G = F.view(dtype = [('p0', F.dtype), ('p1', F.dtype)])
G = np.unique(G)
G

array([( 0, 67), ( 0, 90), ( 4, 16), ..., (65, 72), (67, 72), (67, 90)],
      dtype=[('p0', '<i8'), ('p1', '<i8')])

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [110]:
C = np.bincount([1, 1, 2, 3, 4, 4, 6])
A = np.repeat(np.arange(len(C)), C)
A

array([1, 1, 2, ..., 4, 4, 6])

#### 75. How to compute averages using a sliding window over an array? (★★★)

In [111]:
def moving_average(a, n=3):
    ret = np.cumsum(a, dtype = float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n-1:] / n
Z = np.arange(20)
moving_average(Z, n=3)

array([ 1.,  2.,  3., ..., 16., 17., 18.])

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [112]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window +1, window)
    strides = (a.strides[0] ,a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
Z 

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       ...,
       [5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [114]:
Z = np.random.uniform(-1.0, 1.0, 100)
np.negative(Z, out=Z)

array([ 0.52883797,  0.04423834, -0.14077086, ...,  0.10343853,
        0.87954826,  0.58381683])

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [116]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 2.33874372 11.09695637 11.76234302 ... 14.03824932  0.46128397
 12.15122094]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [117]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 1.50049265 14.32927706  6.7240077  ...  8.35876378  0.74552462
   1.84880602]
 [ 1.35513412 14.49255429  6.83277953 ...  8.49175718  0.80018821
   2.004736  ]
 [ 6.9157214   2.55545091  3.48952584 ...  2.71903772  2.18397129
   4.55790272]
 ...
 [ 2.91928424 14.63986872  4.99273142 ...  7.39511782  5.24932851
   6.10127482]
 [14.02930596  0.36831159  3.32721431 ...  3.77599661  3.58486311
  11.65675026]
 [ 5.89335607  7.20355118  1.06440634 ...  1.98183161  0.43155595
   3.09366099]]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)